version: '3.8'

services:
  product-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: productdb
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - product-db-data:/var/lib/mysql
    networks:
      - product-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

  product-api:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      product-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://product-db:3306/productdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      - product-network
      - msa-order-api_order-network  # order-api의 Kafka에 접근하기 위해 추가

networks:
  product-network:
    driver: bridge
  msa-order-api_order-network:
    external: true  # order-api의 네트워크를 외부 네트워크로 참조

volumes:
  product-db-data: